import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, UserButton, SignInButton, SignedIn, SignedOut } from '@clerk/nextjs';
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // Wrap everything in ClerkProvider
    <ClerkProvider>
      <html lang="en">
        <body>
          {/* Add a generic header so we can sign out */}
          <header className="p-4 border-b flex justify-between items-center">
            <h1 className="font-bold text-xl">🏌️‍♂️ AI Caddie</h1>
            <SignedIn>
              <UserButton />
            </SignedIn>
            <SignedOut>
              <SignInButton />
            </SignedOut>
          </header>
          
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}